import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UseQueryResult } from "@tanstack/react-query";
import type { Job, JobPlan } from "@shared/types";
import {
  confirmReviewCompleted,
  createDryRun,
  createExecution,
  fetchJob,
  fetchJobPlan,
  reportReviewProblem,
} from "@shared/api/jobs";

/**
 * Automation jobs are server state and TanStack Query owns them. There is no
 * job store beside this cache, and no client-held "current job id" that the
 * URL does not already carry.
 *
 * Freshness comes from the backend's /events stream, which invalidates these
 * keys; there is no polling interval. The initial GET still runs on every
 * mount, so a deep link or a reload shows the current state without waiting
 * for an event to arrive.
 */

/**
 * Cache identity for a job is the account AND the job.
 *
 * The fetch itself refuses a job belonging to another account, but a key of
 * ["job", jobId] alone would let a cached entry populated under one account
 * be served instantly under another — drawn beneath the wrong account header
 * until a refetch happened to correct it. Including the account means there
 * is simply no entry to reuse.
 */
export function jobQueryKey(accountId: string, jobId: string) {
  return ["job", accountId, jobId] as const;
}

export function jobPlanQueryKey(accountId: string, jobId: string) {
  return ["job-plan", accountId, jobId] as const;
}

export function useJobQuery(
  jobId: string,
  expectedAccountId: string,
): UseQueryResult<Job | null, Error> {
  return useQuery({
    queryKey: jobQueryKey(expectedAccountId, jobId),
    queryFn: ({ signal }) => fetchJob(jobId, expectedAccountId, signal),
  });
}

export function useJobPlanQuery(
  accountId: string,
  jobId: string,
  enabled: boolean,
): UseQueryResult<JobPlan, Error> {
  return useQuery({
    queryKey: jobPlanQueryKey(accountId, jobId),
    queryFn: ({ signal }) => fetchJobPlan(jobId, signal),
    enabled,
  });
}

export interface StartDryRunInput {
  readonly accountId: string;
  readonly typedInput: unknown;
  /**
   * Generated by the caller once per actual submit attempt and passed here as
   * a mutation variable, so a retry of that attempt reuses the same key.
   * Generating it inside the mutation function would mint a new key per
   * retry — which is how one click becomes two automations.
   */
  readonly idempotencyKey: string;
}

/**
 * Starts a dry run.
 *
 * The caller generates the idempotency key once per submit attempt and passes
 * it as a mutation variable, so a retry of the same attempt reuses the same
 * cannot produce a second job. A new click is a new attempt and a new key.
 */
export function useStartDryRun() {
  return useMutation({
    mutationFn: async (input: StartDryRunInput) =>
      createDryRun({
        accountId: input.accountId,
        typedInput: input.typedInput,
        idempotencyKey: input.idempotencyKey,
      }),
  });
}

/**
 * Authorizes execution of a verified dry-run.
 *
 * Returns the EXECUTION job id, which is a different job from its parent.
 * Callers must route to it rather than continuing to display the dry-run.
 */
export function useAuthorizeExecution(accountId: string, dryRunJobId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    // Same reasoning as the dry run: the key belongs to the attempt, not to
    // the function body.
    mutationFn: async (idempotencyKey: string) => createExecution(dryRunJobId, idempotencyKey),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: jobQueryKey(accountId, dryRunJobId) });
    },
  });
}

/**
 * Records the employee's completion attestation.
 *
 * Nothing is written optimistically. The confirmed state is whatever the
 * refetched job says it is — an attestation the backend refused must not look
 * like one it accepted.
 */
export function useConfirmReview(accountId: string, jobId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => confirmReviewCompleted(jobId),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: jobQueryKey(accountId, jobId) });
      await queryClient.invalidateQueries({ queryKey: ["jobs"] });
    },
  });
}

/** Reports that the review did not complete cleanly. Same refetch discipline. */
export function useReportProblem(accountId: string, jobId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => reportReviewProblem(jobId),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: jobQueryKey(accountId, jobId) });
      await queryClient.invalidateQueries({ queryKey: ["jobs"] });
    },
  });
}
