import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UseQueryResult } from "@tanstack/react-query";
import type { Job, JobPlan } from "@shared/types";
import { createDryRun, createExecution, fetchJob, fetchJobPlan } from "@shared/api/jobs";
import { isJobInFlight } from "@shared/utils/jobStatus";

/**
 * Automation jobs are server state and TanStack Query owns them. There is no
 * job store beside this cache, and no client-held "current job id" that the
 * URL does not already carry.
 *
 * While a job is genuinely moving, the job query refetches on an interval.
 * That is a stand-in for the backend's /events stream, not a parallel
 * mechanism: the query key is what SSE will invalidate, so switching to it
 * later removes the interval and changes nothing else.
 */

const POLL_INTERVAL_MS = 2000;

/**
 * Cache identity for a job is the account AND the job.
 *
 * The fetch itself refuses a job belonging to another account, but a key of
 * ["job", jobId] alone would let a cached entry populated under one account
 * be served instantly under another — drawn beneath the wrong account header
 * until a refetch happened to correct it. Including the account means there
 * is simply no entry to reuse.
 */
export function jobQueryKey(accountId: string, jobId: string) {
  return ["job", accountId, jobId] as const;
}

export function jobPlanQueryKey(accountId: string, jobId: string) {
  return ["job-plan", accountId, jobId] as const;
}

export function useJobQuery(
  jobId: string,
  expectedAccountId: string,
): UseQueryResult<Job | null, Error> {
  return useQuery({
    queryKey: jobQueryKey(expectedAccountId, jobId),
    queryFn: ({ signal }) => fetchJob(jobId, expectedAccountId, signal),
    // Polling stops the moment the job reaches a state nothing advances on
    // its own — a decision or a failure waits for a person, not for time.
    refetchInterval: (query) => {
      const job = query.state.data;
      if (job === undefined || job === null) return false;
      return isJobInFlight(job.status) ? POLL_INTERVAL_MS : false;
    },
  });
}

export function useJobPlanQuery(
  accountId: string,
  jobId: string,
  enabled: boolean,
): UseQueryResult<JobPlan, Error> {
  return useQuery({
    queryKey: jobPlanQueryKey(accountId, jobId),
    queryFn: ({ signal }) => fetchJobPlan(jobId, signal),
    enabled,
  });
}

export interface StartDryRunInput {
  readonly accountId: string;
  readonly typedInput: unknown;
  /**
   * Generated by the caller once per actual submit attempt and passed here as
   * a mutation variable, so a retry of that attempt reuses the same key.
   * Generating it inside the mutation function would mint a new key per
   * retry — which is how one click becomes two automations.
   */
  readonly idempotencyKey: string;
}

/**
 * Starts a dry run.
 *
 * The caller generates the idempotency key once per submit attempt and passes
 * it as a mutation variable, so a retry of the same attempt reuses the same
 * cannot produce a second job. A new click is a new attempt and a new key.
 */
export function useStartDryRun() {
  return useMutation({
    mutationFn: async (input: StartDryRunInput) =>
      createDryRun({
        accountId: input.accountId,
        typedInput: input.typedInput,
        idempotencyKey: input.idempotencyKey,
      }),
  });
}

/**
 * Authorizes execution of a verified dry-run.
 *
 * Returns the EXECUTION job id, which is a different job from its parent.
 * Callers must route to it rather than continuing to display the dry-run.
 */
export function useAuthorizeExecution(accountId: string, dryRunJobId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    // Same reasoning as the dry run: the key belongs to the attempt, not to
    // the function body.
    mutationFn: async (idempotencyKey: string) => createExecution(dryRunJobId, idempotencyKey),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: jobQueryKey(accountId, dryRunJobId) });
    },
  });
}
